services:
  - type: web
    name: octolab-backend
    env: node
    plan: free
    buildCommand: npm install && npm rebuild sqlite3
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        fromService:
          type: web
          name: octolab-frontend
          property: url
    healthCheckPath: /api/health